**Numpy - Numerical Python**

Advantages of Numpy Arrays

1.   Allows several mathematical operations
2.   Faster Operation




In [3]:
import numpy as np

In [4]:
# List time taken
from time import process_time

In [5]:
#Time Taken by a list

python_list = [i for i in range(10000)]
start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()
print(end_time-start_time)


0.0007895229999999032


In [6]:
np_array = np.array([i for i in range(100000)])
start_time = process_time()
np_array += 5
end_time = process_time()
print(end_time - start_time)

0.00036260899999973617


In [7]:
#Numpy Array

list = [1,2,3,4,5,6]
print(list)
type(list)

[1, 2, 3, 4, 5, 6]


list

In [8]:
np_array = np.array([1,2,3,4,5,6])
print(np_array)
type(np_array)

[1 2 3 4 5 6]


numpy.ndarray

In [9]:
# create die  array
a = np.array([1,2,3,4,5,6,7])
print(a)

[1 2 3 4 5 6 7]


In [10]:
a.shape

(7,)

In [11]:
b = np.array([(1,2,3,4,5,6),(7,8,9,10,11,12)])
print(b)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [12]:
b.shape

(2, 6)

In [13]:
#initial Placeholder in numpy array

x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [14]:
#create  an numpy array of ones

y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [15]:
#create a numpy  array of valu

z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [16]:
v = np.random.randint(10,100,(3,5))
print(v)

[[83 88 43 57 76]
 [46 13 86 99 47]
 [35 62 57 12 43]]


In [17]:
c = np.linspace(10,30,5)
print(c)

[10. 15. 20. 25. 30.]


In [18]:
b = np.arange(10,30,5)
print(b)

[10 15 20 25]


In [19]:
# convert list to numpy array

list2 = [10,20,30,40,50]
np_array = np.asarray(list2)
print(np_array)
print(type(np_array))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [20]:
list1 = [1,2,3,4,5]
list2 =[6,7,8,9,10]

print(list1+list2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [21]:
a = np.array([1,2,3,4,5])
b =np.array([6,7,8,9,10])

print(a+b)
print(a-b)
print(a*b)
print(a/b)


[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]
